name: portfolio-profissional

services:
  portfolio:
    build:
      context: ./portfolio
      dockerfile: Dockerfile

    container_name: portfolio-profissional

    ports:
      - "3000:3000"

    restart: unless-stopped

    environment:
      NODE_ENV: production